name: CI
on:
  push:
    branches:
        - master
  pull_request:
jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        ts: ['cli', 'zts']
    container:
      image: php:${{ matrix.php }}-${{ matrix.ts }}
    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y "automake" "libtool" "libcrypt-dev"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make xpass
        run: |
          phpize
          ./configure
          make -j"$(nproc)"
      - name: Test xpass
        env:
          TEST_PHP_ARGS: '-q --show-diff'
        run: make test
